<a href="https://colab.research.google.com/github/zaid787x/Hack-o-Week/blob/main/Week_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

data = []
n = int(input("Enter number of sensor readings: "))

for i in range(n):
    val = input(f"Enter reading {i+1} (or press Enter for missing): ")

    if val == "":
        data.append(np.nan)   # missing value
    else:
        data.append(float(val))

df = pd.DataFrame({"distance": data})

print("Raw Data:")
df

Enter number of sensor readings: 10
Enter reading 1 (or press Enter for missing): 50
Enter reading 2 (or press Enter for missing): 40
Enter reading 3 (or press Enter for missing):
Enter reading 4 (or press Enter for missing): 200
Enter reading 5 (or press Enter for missing): 15
Enter reading 6 (or press Enter for missing): 8
Enter reading 7 (or press Enter for missing):
Enter reading 8 (or press Enter for missing): 30
Enter reading 9 (or press Enter for missing): 12
Enter reading 10 (or press Enter for missing): 5
Raw Data:

   distance
0      50.0
1      40.0
2       NaN
3     200.0
4      15.0
5       8.0
6       NaN
7      30.0
8      12.0
9       5.0

In [2]:
print("Missing values:")
print(df.isnull().sum())

# Fill missing with mean
df["distance"].fillna(df["distance"].mean(), inplace=True)

print("\nAfter filling missing values:")
df

Missing values:
distance    2
dtype: int64

After filling missing values:

/tmp/ipykernel_1772/2074474984.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["distance"].fillna(df["distance"].mean(), inplace=True)

   distance
0      50.0
1      40.0
2      45.0
3     200.0
4      15.0
5       8.0
6      45.0
7      30.0
8      12.0
9       5.0

In [3]:
Q1 = df["distance"].quantile(0.25)
Q3 = df["distance"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["distance"] >= lower) & (df["distance"] <= upper)]

print("After removing outliers:")
df

After removing outliers:

   distance
0      50.0
1      40.0
2      45.0
4      15.0
5       8.0
6      45.0
7      30.0
8      12.0
9       5.0

In [4]:
df["distance"] = (df["distance"] - df["distance"].min()) / (df["distance"].max() - df["distance"].min())

print("Normalized Data:")
df

Normalized Data:

/tmp/ipykernel_1772/3132634468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["distance"] = (df["distance"] - df["distance"].min()) / (df["distance"].max() - df["distance"].min())

   distance
0  1.000000
1  0.777778
2  0.888889
4  0.222222
5  0.066667
6  0.888889
7  0.555556
8  0.155556
9  0.000000